"""Central thresholds and paths for the lightweight detection prototype."""
from pathlib import Path

MAX_TRANSACTIONS_PER_WINDOW = 3
WINDOW_SIZE_MINUTES = 10
HIGH_AMOUNT_THRESHOLD = 1_000.0

# Layer 2: behavioral rule thresholds.
DORMANCY_THRESHOLD_DAYS = 45
DORMANCY_AMOUNT_THRESHOLD = 200.0
STRUCTURING_WINDOW_HOURS = 72
STRUCTURING_MIN_PRIOR_TRANSACTIONS = 4
STRUCTURING_SINGLE_THRESHOLD = 1_000.0
STRUCTURING_AGGREGATE_THRESHOLD = 3_500.0
ESCALATION_MULTIPLIER = 4.0
ESCALATION_MIN_HISTORY = 3
ROUND_AMOUNT_DIVISOR = 500
ROUND_AMOUNT_MINIMUM = 500.0

# Layer 3: per-user statistical baseline thresholds.
BASELINE_STD_THRESHOLD = 2.5
BASELINE_MIN_HISTORY = 5
UNUSUAL_HOUR_MIN_HISTORY = 5
GAP_COMPRESSION_RATIO = 0.1
GAP_MIN_HISTORY = 4

PROJECT_ROOT = Path(__file__).resolve().parent
DATABASE_PATH = PROJECT_ROOT / "risk_alerts.db"
SCHEMA_PATH = PROJECT_ROOT / "schema.sql"
SAMPLE_DATA_PATH = PROJECT_ROOT / "sample_transactions.json"
